// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_space_expert = "CgkI377R8oAUEAIQEw"; // <GPGSID>
        public const string achievement_its_over_nine_thousand = "CgkI377R8oAUEAIQDw"; // <GPGSID>
        public const string achievement_space_rookie = "CgkI377R8oAUEAIQEQ"; // <GPGSID>
        public const string achievement_almost_an_ace = "CgkI377R8oAUEAIQDQ"; // <GPGSID>
        public const string achievement_a_good_start = "CgkI377R8oAUEAIQDA"; // <GPGSID>
        public const string achievement_the_lord_of_the_space = "CgkI377R8oAUEAIQEA"; // <GPGSID>
        public const string achievement_space_allstar = "CgkI377R8oAUEAIQFQ"; // <GPGSID>
        public const string achievement_space_intermediate = "CgkI377R8oAUEAIQEg"; // <GPGSID>
        public const string achievement_a_true_ace = "CgkI377R8oAUEAIQDg"; // <GPGSID>
        public const string leaderboard_score_ranking = "CgkI377R8oAUEAIQAQ"; // <GPGSID>
        public const string achievement_space_master = "CgkI377R8oAUEAIQFA"; // <GPGSID>

}

