// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_100_games = "CgkI377R8oAUEAIQBw"; // <GPGSID>
        public const string achievement_200_games = "CgkI377R8oAUEAIQCA"; // <GPGSID>
        public const string achievement_nearly_an_ace = "CgkI377R8oAUEAIQAw"; // <GPGSID>
        public const string achievement_its_over_9000_ = "CgkI377R8oAUEAIQBQ"; // <GPGSID>
        public const string achievement_a_good_start = "CgkI377R8oAUEAIQAg"; // <GPGSID>
        public const string leaderboard_score_ranking = "CgkI377R8oAUEAIQAQ"; // <GPGSID>
        public const string achievement_10_games = "CgkI377R8oAUEAIQBg"; // <GPGSID>
        public const string achievement_a_true_ace = "CgkI377R8oAUEAIQBA"; // <GPGSID>

}

